# Docker Compose (v2)



version: "2"

services:

  web:

    image: mankev/site-wxt_web

    environment:

      - DRUPAL_SETTINGS=production
 
      - http_proxy=${HTTP_PROXY}

      - https_proxy=${HTTP_PROXY}

      - HTTP_PROXY=${HTTP_PROXY}

      - HTTPS_PROXY=${HTTP_PROXY}

    volumes:

      #- ${WEBAPP_STORAGE_HOME}/www/html/sites/default/conf/drupal/settings.php:/var/www/html/sites/default/settings.php:ro

      - ${WEBAPP_STORAGE_HOME}/www/html/sites/default/files:/var/www/html/sites/default/files

    ports:

      - '9000:9000'

  nginx:

    image: mankev/site-wxt_nginx

    volumes:

     - ${WEBAPP_STORAGE_HOME}/www/html/sites/default/files:/var/www/html/sites/default/files

     #- ${WEBAPP_STORAGE_HOME}/www/html/sites/default/conf/nginx.conf:/etc/nginx/nginx.conf:ro

    ports:

      - '80:80'

    depends_on:

      - web

    restart: always




volumes:

  files_data:
