
# Docker Compose (v2)



version: "2"

services:

  web:

    build:

      context: docker/images/prod

      args:

        - http_proxy=${HTTP_PROXY}

        - https_proxy=${HTTP_PROXY}

        - HTTP_PROXY=${HTTP_PROXY}

        - HTTPS_PROXY=${HTTP_PROXY}

    environment:

      - DRUPAL_SETTINGS=production

      - http_proxy=${HTTP_PROXY}

      - https_proxy=${HTTP_PROXY}

      - HTTP_PROXY=${HTTP_PROXY}

      - HTTPS_PROXY=${HTTP_PROXY}

    volumes:

      - /var/www/html/sites/default/conf/drupal/settings.php:/var/www/html/sites/default/settings.php:ro

      - /var/www/html/sites/default/files:/var/www/html/sites/default/files

    ports:

      - "9000"

    container_name: sitewxt_web

  nginx:

    build:

      context: docker/images/nginx

    volumes:

     - /var/www/html/sites/default/files:/var/www/html/sites/default/files

     - /var/www/html/sites/default/conf/nginx.conf:/etc/nginx/nginx.conf:ro

    ports:

      - '80:80'

    depends_on:

      - web

    restart: always

    container_name: sitewxt_nginx




volumes:

  files_data:
